function normalize(s: string): string {
  return s.toUpperCase().normalize('NFD').replace(/[̀-ͯ]/g, '')
}

const FEMALE_NAMES = new Set([
  'MARIE','JEANNE','ANNE','CATHERINE','SOPHIE','ISABELLE','CLAIRE','JULIE','LAURE',
  'CAROLE','SYLVIE','NATHALIE','VALERIE','SANDRINE','STEPHANIE','VIRGINIE','CELINE',
  'AURELIE','CAMILLE','EMMA','ALICE','CHLOE','LEA','MANON','SARAH','LAURA','LUCIE',
  'PAULINE','AMANDINE','ELODIE','MARINE','JESSICA','JENNIFER','AUDREY','EMILIE',
  'MELANIE','VANESSA','ANGELIQUE','CHRISTELLE','PATRICIA','MARTINE','BRIGITTE',
  'MONIQUE','FRANCOISE','ODETTE','PIERRETTE','GENEVIEVE','YVETTE','JACQUELINE',
  'RAYMONDE','MADELEINE','SUZANNE','THERESE','HENRIETTE','RENEE','SIMONE','LOUISE',
  'MARGUERITE','GERMAINE','LEONIE','YVONNE','MARCELLE','BERTHE','HELENE','ELISE',
  'ELISA','BLANDINE','BEATRICE','DELPHINE','LAURENCE','CORINNE','NADEGE','SABRINA',
  'KARINE','SEVERINE','AMELIE','MATHILDE','JUSTINE','LENA','MAEVA','OCEANE','INES',
  'JADE','LILOU','MAYA','NINA','NOEMIE','ZOE','ALICIA','ALEXIA','ANASTASIA','AXELLE',
  'BERNADETTE','CHARLENE','CLEMENCE','COLETTE','CONSTANCE','CORALIE','EDITH',
  'ELEONORE','ELVIRE','ESTELLE','EUGENIE','FANNY','FELICIE','FLORENCE','GAELLE',
  'GHISLAINE','GWENAELLE','IMANE','IRENE','JOCELYNE','JUDITH','JULIETTE','LAURIE',
  'LILIANE','LISA','LISE','LORRAINE','LUCILE','LUCIENNE','MAGALI','MARGOT','MARINA',
  'MARJORIE','MEGANE','MELISSA','MYRIAM','NADINE','NOLWENN','OPHELIE','ORIANE',
  'PERLE','PRISCILLA','RAPHAELLE','REGINE','ROMANE','ROSALIE','ROXANE','SABINE',
  'SALOME','SOLENE','SOLANGE','SOLINE','TATIANA','TIPHAINE','VERONIQUE','VICTOIRE',
  'VIOLETTE','WENDY','YOLANDE','ZINEB','CHARLOTTE','VICTORIA','ELENA','LUNA','ZARA',
  'YASMINE','FATOUMATA','AMINATA','AISSATOU','MARIAM','AICHA','FATIMA','KHADIJA',
  'SOFIA','SARA','AMINA','LEILA','LILA','RIMA','SONIA','SIRINE','ASSIA','WAFA',
  'NAIMA','RACHIDA','LATIFA','HANANE','SAMIRA','DOUNIA','MERYEM','HOUDA','NADIA',
  'RAJA','LAILA','HIND','SALMA','HAJAR','MAJDA','BOUCHRA','SANAA','CELIA','CAPUCINE',
  'ALBANE','AGATHE','ADELE','ADELINE','ADRIENNE','ALINE','AMBRE','ANAELLE','ANAIS',
  'ANISSA','ANNABELLE','APOLLINE','ARMELLE','ASTRID','AURELIE','AURORE','AXELLE',
  'BERENICE','BRIGITTE','CARINE','CASSANDRA','CECILE','CELIA','CHRISTIANE',
  'CLOTHILDE','CYRIELLE','DAPHNEE','DIANE','DOMITILLE','DOROTHEE','EDWIGE','ELIANE',
  'ELODIE','ELOISE','ELODIE','FAUSTINE','GISELE','GWENOLA','HELOISE','HERMIONE',
  'HUGUETTE','INES','ISAURE','JOELLE','JOSEPHINE','LAETITIA','LAURE','LENA','LILAS',
  'LOUBNA','LUCIE','LUISA','LYDIA','MAELINE','MAEVA','MARGAUX','MARLENE','MATHILDE',
  'MAUREEN','MELINDA','MELODIE','MERYL','MINA','MIRIAM','MORGANE','MURIEL','MYLENE',
  'NAELLE','NOELLIE','NORA','ORANE','ORIANNE','PATRICIA','PENELOPE','PERRINE',
  'PHOEBE','PRISCILLE','RACHEL','ROMY','ROSEMONDE','SABRINA','SCARLETT','SIBYLLE',
  'SIDONIE','SIGRID','SOLINE','TANIA','TESS','THAIS','TIFFANY','VALENTINA',
  'VALERIE','WANDA','YASMINA','ZELIA',
])

export function detectGender(prenom?: string | null): string | null {
  if (!prenom) return null
  const first = normalize(prenom.split(/[\s\-]/)[0])
  if (FEMALE_NAMES.has(first)) return 'F'
  return 'M'
}
